# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', netfields.fields.CidrAddressField(max_length=43)),
                ('qid', models.CharField(max_length=32)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
