# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wdipranges', '0002_iprange_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprange',
            name='cidr',
            field=netfields.fields.CidrAddressField(db_index=True, max_length=43),
        ),
        migrations.AlterField(
            model_name='iprange',
            name='level',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='iprange',
            name='qid',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
