# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdipranges', '0003_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprange',
            name='label',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='iprange',
            name='types_comma',
            field=models.CharField(default='', max_length=512),
        ),
    ]
